// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxVPbm17u9DuaKucbKE5ZlH9K9Wd8K_0',
    appId: '1:940064004637:web:87957332553c1ce8bbc4f4',
    messagingSenderId: '940064004637',
    projectId: 'friend-circle-66cb3',
    authDomain: 'friend-circle-66cb3.firebaseapp.com',
    storageBucket: 'friend-circle-66cb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmS3Bi0-P9CScwyjWlvvnYYcz8r_nZwmU',
    appId: '1:940064004637:android:979387e3f193e36cbbc4f4',
    messagingSenderId: '940064004637',
    projectId: 'friend-circle-66cb3',
    storageBucket: 'friend-circle-66cb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB30Oi6WEj4alXB1DOdLSvTzEGilZpoPu8',
    appId: '1:940064004637:ios:4f97531af4329b8dbbc4f4',
    messagingSenderId: '940064004637',
    projectId: 'friend-circle-66cb3',
    storageBucket: 'friend-circle-66cb3.appspot.com',
    iosClientId: '940064004637-s9p0tce271h9kroh13gq9ccf6dm3vtle.apps.googleusercontent.com',
    iosBundleId: 'com.ibrahim.sengun.friendCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB30Oi6WEj4alXB1DOdLSvTzEGilZpoPu8',
    appId: '1:940064004637:ios:3860dc4636bb4d6cbbc4f4',
    messagingSenderId: '940064004637',
    projectId: 'friend-circle-66cb3',
    storageBucket: 'friend-circle-66cb3.appspot.com',
    iosClientId: '940064004637-k2tfu1lpnniu0fdd9k2bf6bfdv42jjjj.apps.googleusercontent.com',
    iosBundleId: 'com.ibrahim.sengun.friendCircle.RunnerTests',
  );
}
